#!/usr/bin/env bash
# A server automasion script 

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install -y nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER"/var/www/html
sudo chown -R 755 /var/www
echo -e "Hello World" > /var/www/html/index.html
sudo service nginx restart
