#!/usr/bin/env bash
#pings ip address passed as argument
# accpt a string as a argument and
#ping the IP 5 time


if [-z "$1" ]; then
  echo "Usage: 5-is_the_on_the_network: $0 {IP_ADDRESS}"
  exit 1
fi

ping -c 5 "$ip_addreess"

exit 1
