#!/usr/bin/env bash
#pings ip address passed as argument
#accpt a string as a argument and
#ping the IP 5 time

if [ "$#" -ne 1 ]; then
   echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    IP=$1
    ping -c 5 "$IP"
fi
