#!/usr/bin/env bash
#Script displays infinity and beyond indefinitely
#Sleep 2 between each iteration
#receive SIGTERM signal with i am inivcible

#Handle the SIGTERM signal
trap 'echo "I am invincible!!!"' 15

#start the loop
while true; do
	echo "To infinit and beyond"
	sleep 2
done
