#!/usr/bin/env bash
#Script to display the content of the file /etc/passwd, only 
#username, user id and home dirctory path

while read -r string; do
echo "$string" | cut -d : -f 1,3,6;
done < /etc/passwd
