#!/usr/bin/env bash
#Script that displays best school 10 times
#Displays Best School then hi on the 9th iteration

counter=1
while [ $counter -le 10 ]
do
	if [ $counter -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((counter++))
	done 
