#!/usr/bin/env bash
#Script that displays 10 loops
#Display bad luck for 4th loop
#Displays good for 8th loop
#Displays Best School for others

counter=1
while [ $counter -le 10 ]
do
	if [ $counter -eq 4 ]
	then
		echo "bad luck"
	elif [ $counter -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done 
