#!/usr/bin/env bash
#Script to display time for 12 hours and 59 minutes

hour=0
minutes=1
while [ $hour -le 12 ]
do
while [ $minutes -le 59 ]
do
echo "$hours $minutes"
((minutes++))
done
minutes=1
((hours++))
done
