#!/usr/bin/env bash
# configures an ubuntu server's local host
cp / etc / hosts ~/ hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/ hosts.new
sed -i '2i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8.8.8.8 facebook.com' 
~/ hosts.new
cp -f ~/ hosts.new /etc / hosts
rm -f ~/ hosts.new
