#!/usr/bin/env bash

#copy the hostfile
cp etc/hosts ~/hosts.new
sed ... ~/hosts.new
cp -f ~/host.new /etc/hosts

#configure hostfile
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo -a /etc/hosts
