#!/usr/bin/env bash
# script to run nginx as nginx with root priv

# kill apache server
pkill -f apache2
# change ownership
chown nginx:nginx /etc/nginx/nginx.conf
# give permission
chmod 644 /etc/nginx/nginx.conf
# default port
sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
# restart nginx
sudo -u nginx service nginx start
