#!/usr/bin/env bash
# script to run nginx as nginx with root priv

# kill apache server
pkill -f apache2

chown nginx:nginx /etc/nginx/nginx.conf

# give permission
chmod 700 /etc/nginx/nginx.conf

sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default

# restart nginx
sudo service nginx start
